#!/usr/bin/env bash
# Stdio MCP wrapper for MemoryMCP. Point any MCP harness's "command" here —
# env is owned by .mcp.env, so harness configs need no env block.
#
# MCP stdio protocol: NEVER write to stdout from this script; diagnostics
# go to stderr only.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MCP_MAIN="$REPO_ROOT/MemoryMCP/bin/tdai-memory-mcp.mjs"

ENV_FILE="$SCRIPT_DIR/.mcp.env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "[tdai-memory-mcp] $ENV_FILE not found. cp .mcp.env.example .mcp.env and fill it in." >&2
  exit 1
fi
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

# .mcp.env also carries HTTP-mode settings; force stdio for this wrapper.
unset TDAI_MCP_HTTP_PORT TDAI_MCP_HTTP_HOST TDAI_MCP_BINDINGS

# API key fallback: admin key generated by start-memory-core.sh
if [[ -z "${TDAI_API_KEY:-}" && -s "$SCRIPT_DIR/.admin-key" ]]; then
  TDAI_API_KEY="$(cat "$SCRIPT_DIR/.admin-key")"
  export TDAI_API_KEY
fi

# GUI-launched harnesses (Windsurf, Cursor) may not inherit a shell PATH.
find_node() {
  if command -v node >/dev/null 2>&1; then command -v node; return; fi
  for p in /usr/local/bin/node /opt/homebrew/bin/node; do
    [[ -x "$p" ]] && { echo "$p"; return; }
  done
  echo "[tdai-memory-mcp] node not found (need >= 20)" >&2
  exit 1
}
NODE="$(find_node)"

if [[ ! -f "$MCP_MAIN" ]]; then
  echo "[tdai-memory-mcp] $MCP_MAIN missing. Run: cd MemoryMCP && npm install && npm run build" >&2
  exit 1
fi

# Per-project read identity — the SAME resolution the reflect hook uses for
# writes (.tdai-project.env → folder-name registry match → .mcp.env default),
# so a session recalls the memory of the agent its lessons route to.
# Harnesses launch stdio MCP servers with cwd = project dir, hence $PWD.
# shellcheck disable=SC1091
source "$SCRIPT_DIR/_identity.sh"
resolve_project_identity "$PWD"
echo "[tdai-memory-mcp] identity route=${TDAI_IDENTITY_ROUTE} agent=${TDAI_AGENT_ID:-?}" >&2

exec "$NODE" "$MCP_MAIN"
